### ISSUE TITLE
Bad generated faces after large number of epochs

### ISSUE THREAD

**Issue by sebastiangonsal** [aleju/face-generator#2]
Hi,
I have written a gan implementation but find that it starts generating random faces after a lot of iterations after giving good results until starting 5 -6 epochs. 

Did you find your loss to increase in higher iterations or it just got better?

**Comment by aleju** [comment]
Did you write a GAN according to the original algorithm? These often suddenly explode and turn from good to complete garbage. With the DCGAN architecture that happens less often. WGAN has even better stability.

**Comment by sebastiangonsal** [comment]
I did write it according to the DCGAN architecture.  THanks
